Unit strConst;
{ string constants definition }
Interface
Const
     cScenario          ='dreams';
     cVersion           =' Version ';
     cCopyright         =' Copyright (C) ';
     cConfSwitches      ='configured switches: ';
     cPlayMode          ='playmode=';
     cDebugPlay         =' debugplay=';
     cAllocate          ='allocating under script ';
     cBytes             =' bytes';

     cLocTitle       ='Location';
     cDescribeAct    ='describe';
     cNoTHINGS       ='There is no things';
     cTHingThere     ='Things there:';
     cNoVisibleOuts  ='There is no visible outs';
     cOutsHere       ='Outs from here:';
     cNoHumans       ='There is no humans';
     cHumansHere     ='Humans here';
     cNoSuchOut      ='There is no such out';
     cPlayModeOn     ='Play mode turned on';
     cYes            ='Yes';

     cCantConvertID  ='Can`t convert(str->classid):';


implementation
end.